### ISSUE TITLE
Purpose of this repo

### ISSUE THREAD

**Issue by ghost** [multiformats/c-multihashing#1]
Is this to hold code examples? If so, I think these should be part of the c-multihash repo itself.

Otherwise, nevermind, carry on :)

**Comment by Kubuxu** [comment]
No, we are spiting C implementation of multihash into two repos:
- c-multihash - decoding and encoding multihash format
- c-multihashing - lib and binary with hashing algs built in

**Comment by ghost** [comment]
Ah yep that makes sense, thanks
